### ISSUE TITLE
sync with online taskserver

### ISSUE THREAD

**Issue by hymie0** [jschlatow/taskopen#103]
Hello.

I hate to call this an "issue", but I don't know how to contact somebody directly through github.

For the record, taskopen is awesome.  Multi-line notes in a text file are the main thing (imho) that taskwarrior was missing.

I have started using inthe.am as an online taskserver.  I see that my taskopen notes don't sync, only the references to the taskopen notes.  I assume there's no way around that, whether I use inthe.am or another sync service?

**Comment by ValiValpas** [comment]
Hi @hymie0, first of all, I'm very glad you appreciate taskopen.

I'm afraid there is no way to sync your notes with a taskserver instance, i.e. you need a separate sync solution for that. It might depend on the type of notes you're using. Here are a couple of ideas that just came to my mind:
* You could store and edit your notes online (e.g. Google Drive).
* Put your notes into an automatically synchronised folder (dropbox, git annex, etc.).
* You could synchronise your notes manually, e.g. using some webdav services or similar (e.g. owncloud).
* You can trigger a manual synchronisation by adding e.g. a hook to the taskwarrior sync command. You could also use taskopen to filter what notes are still relevant for synchronisation and execute some copy/sync operation on those files, like `taskopen -b -x "syncnote $FILE"`.
