### ISSUE TITLE
Auto-run 'task annotate' on missing annotations

### ISSUE THREAD

**Issue by dbogdanov** [jschlatow/taskopen#123]
Currently, to add a text file with notes for a task, one has to run two commands, `task annotate` and `taskopen`. Would it be possible to add an option to automatically create the required annotations (```task 144 annotate Notes```) and then open them in such cases? This would solve the use-case below.
```
➜  ~ task add TEST
Created task 144.
➜  ~ taskopen 144
No compatible annotation found.
```

**Comment by Kevin-Mok** [comment]
I made a [fish function](https://git.kevin-mok.com/Kevin-Mok/linux-config/src/branch/master/dot_config/fish/functions/task/task-notes.fish) to do this for me, but yes, this would be a useful feature.

```fish
function task-notes
    task $argv[1] annotate Notes
    and taskopen $argv[1]
end
```

**Comment by ValiValpas** [comment]
@dbogdanov, @Kevin-Mok 
Please have a look at the `NO_ANNOTATION_HOOK` configuration variable and the `addnote` script in the scripts directory. The `NO_ANNOTATION_HOOK` is executed if the task does not have any annotation.

**Comment by dbogdanov** [comment]
Thank you, this solves the issue. Perhaps adding this info to the "Add default notes" section of the README will help.
