### ISSUE TITLE
Cannot find the attach_vifm script

### ISSUE THREAD

**Issue by lyndhurst** [jschlatow/taskopen#128]
Hi,

I would like to try out the [attach_vifm](https://github.com/ValiValpas/taskopen#attach_vifm-by-artur-shaik) script referred to in the README, but I cannot find a link to it. I searched with google,  GitHub, and the taskwarrior tools page  to no avail.

I thought it would be bundled with `taskopen` but I cannot find it or use the `attach_vifm` commands after a successful install...

Am I missing something?
Thanks for your time.

**Comment by jschlatow** [comment]
@lyndhurst, sorry for the late reply. The script comes with taskopen and is found in the this repository in the script folder. It should be installed with taskopen. How have you installed taskopen on your system and what Linux distribution are you using? The search path for taskopen scripts is set in taskopenrc via `PATH_EXT`.

**Comment by lyndhurst** [comment]
I am on a Ubuntu 18 machine, the script was indeed installed with taskopen at `/usr/share/taskopen/scripts/attach_vifm`. I do not know why, but I got the idea in my head that it was a separate script to be installed so I looked everywhere, but the right place :)
Following the README instructions worked like a charm. Thank you for your reply.
