### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by rhaynes74** [jschlatow/taskopen#130]
Hi folks, first time user here, I am having problems with the install on the mac os, using zsh. 

smatm0013:taskopen:% sudo make PREFIX=/usr                                                    <master ✗>
gzip -c doc/man/taskopen.1 > doc/man/taskopen.1.gz
gzip -c doc/man/taskopenrc.5 > doc/man/taskopenrc.5.gz
sed s',#PATH_EXT=.*,&\nPATH_EXT=/usr/share/taskopen/scripts,' taskopen > taskopen.pl
sed -i'.bak' s',/usr/bin/perl,/usr/bin/perl,' taskopen.pl

smatm0013:taskopen:% sudo make PREFIX=/usr install                                            <master ✗>
gzip -c doc/man/taskopen.1 > doc/man/taskopen.1.gz
gzip -c doc/man/taskopenrc.5 > doc/man/taskopenrc.5.gz
sed s',#PATH_EXT=.*,&\nPATH_EXT=/usr/share/taskopen/scripts,' taskopen > taskopen.pl
sed -i'.bak' s',/usr/bin/perl,/usr/bin/perl,' taskopen.pl
mkdir -p //usr/bin
install -m 0755 taskopen.pl //usr/bin/taskopen
install: //usr/bin/taskopen: Operation not permitted
make: *** [install] Error 71

Those // in front of usr/bin doesn't look right to me, I will admit that the Makefile knowledge is pretty rusty these days.

**Comment by jschlatow** [comment]
@rhaynes74 typically the // does not cause any issues but this may be different on mac os. Could you please try the following and report back with the results:
```
sudo ls /usr/bin/taskopen
sudo touch //usr/bin/taskopen
sudo ls //usr/bin/taskopen
sudo ls /usr/bin/taskopen
```

**Comment by rhaynes74** [comment]
Thanks for the response.  Here is the output.

sudo ls /usr/bin/taskopen <master>
Password:
ls: /usr/bin/taskopen: No such file or directory

sudo touch //usr/bin/taskopen <master ✗>

touch: //usr/bin/taskopen: Operation not permitted

sudo ls //usr/bin/taskopen
ls: //usr/bin/taskopen: No such file or directory

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
@rhaynes74 does it make a difference if you do 
```
sudo touch /usr/bin/taskopen
```
?

**Comment by rhaynes74** [comment]
Hi - thanks for the suggestion, but:

sudo touch /usr/bin/taskopen <master ✗>
touch: /usr/bin/taskopen: Operation not permitted


Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
Apparently `/usr/bin` is protected by Apple's System Integrity Protection so that even root cannot write to this directoy. I'd recommend using a different PREFIX (e.g. `/usr/local`) to install taskopen into `/usr/local/bin` but this depends on your `$PATH`. Can you please check whether `/usr/local/bin/` is in your `$PATH` variable (if not add it) and try installing taskopen with `PREFIX=/usr/local`?

For later reference: This is related to #76

**Comment by rhaynes74** [comment]
Fantastic, this worked, many thanks for your efforts.  (I did use a stackoverflow solution to install the required JSON).

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
Thank you for your interest in taskopen.
