### ISSUE TITLE
"local" urls

### ISSUE THREAD

**Issue by rhaynes74** [jschlatow/taskopen#131]
Good day - taskopen doesn't seem to want to open local URLs like x-devonthink-item://7D425B20-EB31-4589-ACBA-A71D4F22A99B on the mac, the os does open them (spotlight ), anyway to configure the types of attachments that can be opened?

**Comment by jschlatow** [comment]
That is probably only a matter of configuration.

Can you check whether you can open these URLs on the command line with `open x-devonthink-item://...`?
If this is the case, make sure, you can try adding the following line to your `~/.taskopenrc` file:
```
FILE_REGEX="\.|\/|~|:\/\/"
```

If this does not help, please post the output of `taskopen -V` so that I can have a look at your configuration.

**Comment by rhaynes74** [comment]
Good day - followed the steps but no dice.  I did try with and without brackets in the local url in the annotation.  I did also confirm that

open x-devonthink-item://7D425B20-EB31-4589-ACBA-A71D4F22A99B

works from the command line.

Here is the output from taskopen -V:

ID Age Description Urg
 1 24s This is a test 0.8
 2020-11-17
 [test](x-devonthink-item://7D425B20-EB31-4589-ACBA-A71D4F22A99B)

1 task
smatm0013:~:% taskopen 1
No compatible annotation found.
smatm0013:~:% taskopen -V

Taskopen, release v1.1.4, revision 286 (879c0ff)
Copyright 2010-2016, Johannes Schlatow.

Environment
 Platform: darwin
 Perl: v5.28.2
 Taskwarrior: 2.5.1
 xdg-open: N/A on OSX
 Configuration: /Users/rhaynes/.taskopenrc

Current configuration
 Binaries and paths:
 BROWSER = open
 TASKBIN = task rc.verbose=off rc.json.array=on
 EDITOR = vim
 FILE_CMD = open
 PATH = /usr/local/opt/python@3.8/bin:/Users/rhaynes/.gem/ruby/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/sbin:/Users/rhaynes/.nix-profile/bin:/bin:/usr/bin:/Users/rhaynes/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/rhaynes/.local/bin/:/Users/rhaynes/go/bin

 Others:
 NOTES_FOLDER = $HOME/tasknotes/
 NOTES_EXT = .txt
 NOTES_FILE = $HOME/tasknotes/UUID.txt
 NOTES_CMD = vim "$HOME/tasknotes/UUID.txt"
 DEFAULT_FILTER = status.is:pending
 DEFAULT_SORT =
 current:
 DEFAULT-i = ls -la
 current: ls -la
 DEFAULT-x = $FILE
 DEBUG = 0
 NOTES_REGEX = Notes
 BROWSER_REGEX = www|http
 FILE_REGEX = \.|\/|~|:\/\/
 TEXT_REGEX =
 NO_ANNOTATION_HOOK =
 TASK_ATTRIBUTES =
 Custom regex commands:

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
Sorry, my inital suggestion for `FILE_REGEX` was incomplete.

Are your annotations only containing the bare local URLs or do you want a special format such as the `[Name](URL)` notation?
In the former case, `FILE_REGEX="\.|\/|~|.*:\/\/"` should do the trick. For the latter, you can add a custom regex:

```
FILE_REGEX="\.|\/|~"
CUSTOM4_REGEX='\[.*\]\((.*:\/\/.*)\)'
CUSTOM4_CMD="open $LAST_MATCH"
```

**Comment by rhaynes74** [comment]
Hi - might be good to allow the [name](link) format.  I will give it a try.  Thanks for your suggestion - by the way do you know of the taskn package is still being used? Or is there a replacement with similar functionality?

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
Do you mean tasknote? I believe it's functionality is fully covered by taskopen.

Unfortunately, most of the functionality of taskopen is obfuscated by a bizarre layer of command line arguments and configuration options. It can do magic but you need to study it first. I have some ideas for a rewrite to make all this much more usable but have only just started with the documentation in the [wiki](../wiki/2.0). Stay tuned.

Nonetheless, let me know what functionality you would like to see in taskopen and I will help you with the configuration.

**Comment by rhaynes74** [comment]
Hi - many thanks for your response.  Yes, I do mean tasknote.  Here is what I would like to have ( :-) )

i) ability to add files to tasks - preferably from the command line:

taskopen n addfile file*.pdf

ii) ability to add markdown notes to tasks

iii) ability to add/link files to notes

iv) ability to add/link notes to files

(I think about iii) and iv) as being different!

v) ability to open task list/notes/ annotations/ files from a statically generated website (likely this is provided by some package now but I haven’t had a chance to look into it).

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
What taskopen can do is link objects such as files, notes and urls to tasks. Thus, linking files to notes or vice versa is out of scope.
Have you already looked at the manpage, particularly the examples section?

**Comment by rhaynes74** [comment]
Yes I have, thanks!  These are more wish list items!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by jschlatow** [comment]
Okay, i) and ii) are already possible with taskopen (please let me know if you need assistance with the configuration) whereas iii) and iv) seem out of scope if I understand them correctly. For v) I am not sure how taskopen might help. Can you provide more details?

**Comment by rhaynes74** [comment]
Thanks for the quick reply.  iii) and iv) does appear to be out of the current scope, but I would like to make sure that any such solution would be compatible with files and notes added to tasks via taskopen.    Likewise with v).
