### ISSUE TITLE
support for (cb)thunderlink

### ISSUE THREAD

**Issue by gour** [jschlatow/taskopen#138]
Hello,

Hello,

I'd like to integrate Thunderbird with Taskwarrior by using [cbthunderlink](https://github.com/CamielBouchier/cb_thunderlink) addon-on which does work correctly from within my (GNOME) terminal, iow. clicking on a pasted link generated by Thunderbird, jump to the relevant message in TB.

However, when I try put such (cb)thunderlink in Taskwarrior's description or annotation, it does not work.

Any clue what am I missing in Taskopen or Taskwarrior to take advantage of the integration?

**Comment by jschlatow** [comment]
Hi @gour,

not knowing how cbthunderlink works, it is hard to tell what the missing piece is without any further information. I couldn't find in the cbthunderlink docs how the system is configured to know how to open the link.

What you need to do is to associate the url in your taskopenrc with a command. If you post how your taskopenrc looks like at the moment, I could give you assistance.

**Comment by gour** [comment]
Hello @jschlatow ,

> not knowing how cbthunderlink works, it is hard to tell what the missing piece is without any further information. I couldn't find in the cbthunderlink docs how the system is configured to know how to open the link.

I have decided to return back to Claws-mail since I prefer it as mailer and it can be more easily integrated with Taskwarrior/taskopen...

> What you need to do is to associate the url in your taskopenrc with a command. If you post how your taskopenrc looks like at the moment, I could give you assistance.

In Claws I need to create (via Actions feature) a `tw` task and annotate it with something like:

`task ann 189 -- claws-mail -- select/home/gour/.claws-mail/imapcache/mail-server/user-id/INBOX/16321`

and then `taskopen` can use it when invoked with `open 189 -x` :-)


Sincerely,
Gour
p.s. How is 2.' Nom-rewrite going on?

**Comment by jschlatow** [comment]
@gour, thanks for the update and +1 for using claws-mail.

Re. the nim-rewrite: The first version is basically completed, yet it's still lacking proper documentation. My intention was to update the man pages before releasing the first version. If you want to give it a try already, you can use the wiki as documentation though.
