### ISSUE TITLE
Org-roam-protocol Support

### ISSUE THREAD

**Issue by jonathanabennett** [jschlatow/taskopen#147]
I'm porting this request over from the Discord server.

What I'd love is to put "org-roam" in the annotation then have taskopen open a URL that looks like this: org-protocol://roam-ref\?template=r\&ref={Project from Task || 'taskwarrior'}\&title={Description from Task}

Basically, if you're using Org-roam to store your project notes, you might want to be able to look up and access your org-roam graph from your task via task-open. Broadly, this is just org-protocol support. Org-roam-protocol just adds a few special features around UUIDs and graph linking.

**Comment by jschlatow** [comment]
Hi @jonathanabennett, this is pretty straightforward. With taskopen 2.0 you could even use an "org-roam" tag instead of an annotation. Let me demonstrate this with a taskopenrc snippet:

```
[General]
task_attributes = project, description

[Actions]
orgroam.target = tags
orgroam.regex = "org-roam"
orgroam.command = "echo \"org-protocol://roam-ref?template=r&ref={$TASK_PROJECT || 'taskwarrior'}&title={$TASK_DESCRIPTION}\""
```

Note that you need to replace 'echo' with your URL opener.
