### ISSUE TITLE
integration with (neo)mutt via msgid

### ISSUE THREAD

**Issue by gour** [jschlatow/taskopen#148]
Hello, I'd like to integrate (neo)mutt with Taskwarrior as I did with [Claws-mail](https://claws-mail.org/faq/index.php/Using_Claws_Mail_with_other_programs#Integrating_Claws-mail_with_Taskwarrior) where I use `xdg-mime` mechanism.

It was easy since Claws-mail can open message passed as message-filename, while (neo)mutt can only open via `msgid`.

My integration script adds annotation so it looks like:

```
171  4h   email inbox      "Some task (2022-06-17 08:32:38)"                      
                             17.6.2022. 1138994717085.1134239284236.2047430149.0.330942JL.2002@some.domain.com
```

where the string denotes `msgid`.

There is [script](https://github.com/alkim0/task-attach/blob/master/bin/open-via-mutt) to open (neo)mutt message by passing `msgid` or it can be done in a straightforward way with:

```
neomutt -e "push '<search>~i MESSAGE-ID<enter>'"
```

Now, considering that both (neo)mutt and taskwarrior are CLI-apps, I do not required xdg-mime integration, but wonder if there is an easy way to configure Taskopen that it uses the above command when opening tasks annotated with (neo)mutt's `msgid`?

I can install 2.0beta if required...

**Comment by jschlatow** [comment]
@gour, the way to go is to define a regex that matches the annotation. You can use regex groups so that the msgid is will be made available in the environment variable `$LAST_MATCH` by taskopen. Please have a look at the usage example in the [README](https://github.com/jschlatow/taskopen/tree/ea1dc9b7ef2028143503af2807198fbb6c0bc2c0#customised-annotation-filtering).

**Comment by gour** [comment]
> @gour, the way to go is to define a regex that matches the annotation. You can use regex groups so that the msgid is will be made available in the environment variable `$LAST_MATCH` by taskopen. 

Thanks a lot!

I assume I need 2.0beta for that?

**Comment by jschlatow** [comment]
The example from the README is for 2.0, yet the feature was already implemented in 1.x only with a different config syntax (see [taskopenrc.5](https://github.com/jschlatow/taskopen/blob/v1.1.5/doc/man/taskopenrc.5#L148).
