### ISSUE TITLE
taskopen runs garbage collection

### ISSUE THREAD

**Issue by jneidel** [jschlatow/taskopen#165]
taskopen runs taskwarriors garbage collection, so it messes with the ids.

Showcase how this leads to unexpected results:
<img width="883" alt="Screenshot 2023-09-18 at 10 05 45" src="https://github.com/jschlatow/taskopen/assets/25589715/a50b019b-497c-43ff-83c4-983f35f2c510">

Because taskopen ran the garbage collection, id 17 is not "Task 2" anymore, but "Task 3"

What you would expect to happen:
<img width="897" alt="Screenshot 2023-09-18 at 10 07 08" src="https://github.com/jschlatow/taskopen/assets/25589715/989124e2-9455-484d-a3a7-53c86f7baeae">

Disabling garbage collection with `rc.gc=off` leads to the expected behavior.

This should be built into the script :)

**Comment by jschlatow** [comment]
Thanks @jneidel for reporting this. Since you already suggested a solution: Would you like to implement it yourself? The correct place would be in the `taskwarrior.nim` file, which defines the default arguments for taskwarrior.
