### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by benjaminweb** [jschlatow/taskopen#76]
% make PREFIX=/usr
rm -f taskopen.pl
sed '/#PATH_EXT=/ a\
    PATH_EXT=/usr/share/taskopen/scripts' taskopen > taskopen.pl
sed: 1: "/#PATH_EXT=/ aPATH_EXT= ...": command a expects \ followed by text
make: **\* [taskopen.pl] Error 1

same happens by executing a make only

**Comment by ross-ops** [comment]
Hello! I am having the same issue, have tried your steps above to no avail. Completely understand that this project is not aimed at MacOS, and wouldn't bother if it wasn't for a mac being my work's daily driver of choice. 

Just to be clear, I get: 
```✗| → make PREFIX=/usr
gzip -c doc/man/taskopen.1 > doc/man/taskopen.1.gz
gzip -c doc/man/taskopenrc.5 > doc/man/taskopenrc.5.gz
sed s',#PATH_EXT=.*,&\nPATH_EXT=/usr/share/taskopen/scripts,' taskopen > taskopen.pl
sed -i'.bak' s',/usr/bin/perl,/usr/bin/perl,' taskopen.pl```

...when trying to make your project. 

Thanks in advance

Ross

**Comment by ValiValpas** [comment]
@ross-ops I don't see any error message in your quote. Can you please provide the complete output (including the command you're executing) and/or a description of the incorrect behaviour?

**Comment by ross-ops** [comment]
Sorry sure :)

```
$ make PREFIX=/usr
gzip -c doc/man/taskopen.1 > doc/man/taskopen.1.gz
gzip -c doc/man/taskopenrc.5 > doc/man/taskopenrc.5.gz
sed s',#PATH_EXT=.*,&\nPATH_EXT=/usr/share/taskopen/scripts,' taskopen > taskopen.pl
sed -i'.bak' s',/usr/bin/perl,/usr/bin/perl,' taskopen.pl

$ make PREFIX=/usr install
gzip -c doc/man/taskopen.1 > doc/man/taskopen.1.gz
gzip -c doc/man/taskopenrc.5 > doc/man/taskopenrc.5.gz
sed s',#PATH_EXT=.*,&\nPATH_EXT=/usr/share/taskopen/scripts,' taskopen > taskopen.pl
sed -i'.bak' s',/usr/bin/perl,/usr/bin/perl,' taskopen.pl
mkdir -p //usr/bin
install -m 0755 taskopen.pl //usr/bin/taskopen
install: //usr/bin/taskopen: Operation not permitted
make: *** [install] Error 71
```

Thanks for replying

**Comment by ValiValpas** [comment]
@ross-ops the last three lines are the relevant ones. The install operation, which tries to copy the taskopen.pl script to `/usr/bin/taskopen`, fails as this operation is not permitted. This is because you, i.e. your user, rightly do not have write permissions to `/usr/bin`. You must therefore execute `make PREFIX=/usr install` command as root, e.g. by using `sudo`.

**Comment by ross-ops** [comment]
Hi there. Sudo-ing didn't help, but I changed the PREFIX variable to some other folder in my path, and that all sprang into life.

Thanks very much for you project, and time. 
R
