### ISSUE TITLE
RFE: taskopen -I

### ISSUE THREAD

**Issue by linuxcaffe** [jschlatow/taskopen#82]
The -I option causes taskopen to respond in an interactive mode, using something like ncurses, looking something like vit, otherwise doing what it does now, but with the ability to scroll up and down through the listings and effect single-key actions.

This is obviously a demanding feature request for a (distant?) future version.

**Comment by scottkosty** [comment]
Note that VIT integrates very well with taskopen. We can just put
`map o=:! taskopen %TASKID<Return>`
in `.vitrc`

There is one thing to be aware of. If the command you are using to open the annotation does not have a terminal interface (e.g. Firefox/Nautilus), then you will get a lot of messages to STDERR and STDOUT which will make VIT look wierd until a refresh (ctrl + L). The way around this is just to redirect STDERR and STDOUT to /dev/null when you specify the command to run in `.taskopenrc`.
