### ISSUE TITLE
Open the notes of done tasks.

### ISSUE THREAD

**Issue by qrr** [jschlatow/taskopen#87]
Done tasks are stripped of their numeric ID, and AFAIK, you can only refer to them by their UUID, but I did not see any code in taskopen to support direct UUID input. I would love to see such a feature.

The rationale behind this is simple - often, I type quite a lot of information into those notes, and sometimes need to review it even after I've marked the task done.

**Comment by Kevin-Mok** [comment]
> Hi,
> taskopen does support filtering by uuids as it passes the given filter directly to taskwarrior. However, you need to add the flag -A in order to include completed and deleted tasks.

Thanks for this tip. I was just about to open an issue about this for tasks in waiting when GitHub suggested this as a related issue. I tried searching for "pending" as in `There is no task that matches: status.is:pending 10` and also "waiting" so just adding this comment in hopes that it adds this issue to those searches. I probably also should've checked the help flag, but yeah. :sweat_smile:
